states = {
'AK': 'Alaska',
'AL': 'Alabama',
'AR': 'Arkansas',
'AS': 'American Samoa',
'AZ': 'Arizona',
'CA': 'California',
'CO': 'Colorado',
'CT': 'Connecticut',
'DC': 'District of Columbia',
'DE': 'Delaware',
'FL': 'Florida',
'GA': 'Georgia',
'GU': 'Guam',
'HI': 'Hawaii',
'IA': 'Iowa',
'ID': 'Idaho',
'IL': 'Illinois',
'IN': 'Indiana',
'KS': 'Kansas',
'KY': 'Kentucky',
'LA': 'Louisiana',
'MA': 'Massachusetts',
'MD': 'Maryland',
'ME': 'Maine',
'MI': 'Michigan',
'MN': 'Minnesota',
'MO': 'Missouri',
'MP': 'Northern Mariana Islands',
'MS': 'Mississippi',
'MT': 'Montana',
'NA': 'National',
'NC': 'North Carolina',
'ND': 'North Dakota',
'NE': 'Nebraska',
'NH': 'New Hampshire',
'NJ': 'New Jersey',
'NM': 'New Mexico',
'NV': 'Nevada',
'NY': 'New York',
'OH': 'Ohio',
'OK': 'Oklahoma',
'OR': 'Oregon',
'PA': 'Pennsylvania',
'PR': 'Puerto Rico',
'RI': 'Rhode Island',
'SC': 'South Carolina',
'SD': 'South Dakota',
'TN': 'Tennessee',
'TX': 'Texas',
'UT': 'Utah',
'VA': 'Virginia',
'VI': 'Virgin Islands',
'VT': 'Vermont',
'WA': 'Washington',
'WI': 'Wisconsin',
'WV': 'West Virginia',
'WY': 'Wyoming'
}

# Mapping of country names to ISO 3166-1 alpha-2 codes
alpha2 = {
'AF': 'Afghanistan',
'AX': 'Åland Islands',
'AL': 'Albania',
'DZ': 'Algeria',
'AS': 'American Samoa',
'AD': 'Andorra',
'AO': 'Angola',
'AI': 'Anguilla',
'AQ': 'Antarctica',
'AG': 'Antigua and Barbuda',
'AR': 'Argentina',
'AM': 'Armenia',
'AW': 'Aruba',
'AU': 'Australia',
'AT': 'Austria',
'AZ': 'Azerbaijan',
'BS': 'Bahamas',
'BH': 'Bahrain',
'BD': 'Bangladesh',
'BB': 'Barbados',
'BY': 'Belarus',
'BE': 'Belgium',
'BZ': 'Belize',
'BJ': 'Benin',
'BM': 'Bermuda',
'BT': 'Bhutan',
'BO': 'Bolivia, Plurinational State of',
'BQ': 'Bonaire, Sint Eustatius and Saba',
'BA': 'Bosnia and Herzegovina',
'BW': 'Botswana',
'BV': 'Bouvet Island',
'BR': 'Brazil',
'IO': 'British Indian Ocean Territory',
'BN': 'Brunei',
'BG': 'Bulgaria',
'BF': 'Burkina Faso',
'BI': 'Burundi',
'KH': 'Cambodia',
'CM': 'Cameroon',
'CA': 'Canada',
'CV': 'Cape Verde',
'KY': 'Cayman Islands',
'CF': 'Central African Republic',
'TD': 'Chad',
'CL': 'Chile',
'CN': 'China',
'CX': 'Christmas Island',
'CC': 'Cocos (Keeling) Islands',
'CO': 'Colombia',
'KM': 'Comoros',
'CG': 'Congo',
'CD': 'Congo, the Democratic Republic of the',
'CK': 'Cook Islands',
'CR': 'Costa Rica',
'CI': 'Cote d\'Ivoire',
'HR': 'Croatia',
'CU': 'Cuba',
'CW': 'Curaçao',
'CY': 'Cyprus',
'CZ': 'Czech Republic',
'DK': 'Denmark',
'DJ': 'Djibouti',
'DM': 'Dominica',
'DO': 'Dominican Republic',
'EC': 'Ecuador',
'EG': 'Egypt',
'SV': 'El Salvador',
'GQ': 'Equatorial Guinea',
'ER': 'Eritrea',
'EE': 'Estonia',
'ET': 'Ethiopia',
'FK': 'Falkland Islands (Malvinas)',
'FO': 'Faroe Islands',
'FJ': 'Fiji',
'FI': 'Finland',
'FR': 'France',
'GF': 'French Guiana',
'PF': 'French Polynesia',
'TF': 'French Southern Territories',
'GA': 'Gabon',
'GM': 'Gambia',
'GE': 'Georgia',
'DE': 'Germany',
'GH': 'Ghana',
'GI': 'Gibraltar',
'GR': 'Greece',
'GL': 'Greenland',
'GD': 'Grenada',
'GP': 'Guadeloupe',
'GU': 'Guam',
'GT': 'Guatemala',
'GG': 'Guernsey',
'GN': 'Guinea',
'GW': 'Guinea-Bissau',
'GY': 'Guyana',
'HT': 'Haiti',
'HM': 'Heard Island and McDonald Islands',
'VA': 'Holy See',
'HN': 'Honduras',
'HK': 'Hong Kong',
'HU': 'Hungary',
'IS': 'Iceland',
'IN': 'India',
'ID': 'Indonesia',
'IR': 'Iran',
'IQ': 'Iraq',
'IE': 'Ireland',
'IM': 'Isle of Man',
'IL': 'Israel',
'IT': 'Italy',
'JM': 'Jamaica',
'JP': 'Japan',
'JE': 'Jersey',
'JO': 'Jordan',
'KZ': 'Kazakhstan',
'KE': 'Kenya',
'KI': 'Kiribati',
'KP': 'Democratic People\'s Republic of Korea',
'KR': 'Korea, South',
'KW': 'Kuwait',
'KG': 'Kyrgyzstan',
'LA': 'Lao People\'s Democratic Republic',
'LV': 'Latvia',
'LB': 'Lebanon',
'LS': 'Lesotho',
'LR': 'Liberia',
'LY': 'Libya',
'LI': 'Liechtenstein',
'LT': 'Lithuania',
'LU': 'Luxembourg',
'MO': 'Macau',
'MK': 'North Macedonia',
'MG': 'Madagascar',
'MW': 'Malawi',
'MY': 'Malaysia',
'MV': 'Maldives',
'ML': 'Mali',
'MT': 'Malta',
'MH': 'Marshall Islands',
'MQ': 'Martinique',
'MR': 'Mauritania',
'MU': 'Mauritius',
'YT': 'Mayotte',
'MX': 'Mexico',
'FM': 'Federated States of Micronesia',
'MD': 'Republic of Moldova',
'MC': 'Monaco',
'MN': 'Mongolia',
'ME': 'Montenegro',
'MS': 'Montserrat',
'MA': 'Morocco',
'MZ': 'Mozambique',
'MM': 'Myanmar',
'NA': 'Namibia',
'NR': 'Nauru',
'NP': 'Nepal',
'NL': 'Netherlands',
'NC': 'New Caledonia',
'NZ': 'New Zealand',
'NI': 'Nicaragua',
'NE': 'Niger',
'NG': 'Nigeria',
'NU': 'Niue',
'NF': 'Norfolk Island',
'MP': 'Northern Mariana Islands',
'NO': 'Norway',
'OM': 'Oman',
'PK': 'Pakistan',
'PW': 'Palau',
'PS': 'Palestine, State of',
'PA': 'Panama',
'PG': 'Papua New Guinea',
'PY': 'Paraguay',
'PE': 'Peru',
'PH': 'Philippines',
'PN': 'Pitcairn',
'PL': 'Poland',
'PT': 'Portugal',
'PR': 'Puerto Rico',
'QA': 'Qatar',
'RE': 'Reunion',
'RO': 'Romania',
'RU': 'Russian Federation',
'RW': 'Rwanda',
'BL': 'Saint Barthelemy',
'SH': 'Saint Helena, Ascension and Tristan da Cunha',
'KN': 'Saint Kitts and Nevis',
'LC': 'Saint Lucia',
'MF': 'Saint Martin (French part)',
'PM': 'Saint Pierre and Miquelon',
'VC': 'Saint Vincent and the Grenadines',
'WS': 'Samoa',
'SM': 'San Marino',
'ST': 'Sao Tome and Principe',
'SA': 'Saudi Arabia',
'SN': 'Senegal',
'RS': 'Serbia',
'SC': 'Seychelles',
'SL': 'Sierra Leone',
'SG': 'Singapore',
'SX': 'Sint Maarten (Dutch part)',
'SK': 'Slovakia',
'SI': 'Slovenia',
'SB': 'Solomon Islands',
'SO': 'Somalia',
'ZA': 'South Africa',
'GS': 'South Georgia and the South Sandwich Islands',
'SS': 'South Sudan',
'ES': 'Spain',
'LK': 'Sri Lanka',
'SD': 'Sudan',
'SR': 'Suriname',
'SJ': 'Svalbard and Jan Mayen',
'SZ': 'Swaziland',
'SE': 'Sweden',
'CH': 'Switzerland',
'SY': 'Syrian Arab Republic',
'TW': 'Taiwan',
'TJ': 'Tajikistan',
'TZ': 'Tanzania, United Republic of',
'TH': 'Thailand',
'TL': 'Timor-Leste',
'TG': 'Togo',
'TK': 'Tokelau',
'TO': 'Tonga',
'TT': 'Trinidad and Tobago',
'TN': 'Tunisia',
'TR': 'Turkey',
'TM': 'Turkmenistan',
'TC': 'Turks and Caicos Islands',
'TV': 'Tuvalu',
'UG': 'Uganda',
'UA': 'Ukraine',
'AE': 'United Arab Emirates',
'GB': 'United Kingdom',
# 'US': 'United States',
'UM': 'United States Minor Outlying Islands',
'UY': 'Uruguay',
'UZ': 'Uzbekistan',
'VU': 'Vanuatu',
'VE': 'Venezuela, Bolivarian Republic of',
'VN': 'Viet Nam',
'VG': 'Virgin Islands, British',
'VI': 'Virgin Islands, U.S.',
'WF': 'Wallis and Futuna',
'EH': 'Western Sahara',
'YE': 'Yemen',
'ZM': 'Zambia',
'ZW': 'Zimbabwe'
}

# Mapping of country names to ISO 3166-1 alpha-2 codes
alpha3 = {
'ABW': 'Aruba',
'AFG': 'Afghanistan',
'AGO': 'Angola',
'AIA': 'Anguilla',
'ALA': 'Åland Islands',
'ALB': 'Albania',
'AND': 'Andorra',
'ARE': 'United Arab Emirates',
'ARG': 'Argentina',
'ARM': 'Armenia',
'ASM': 'American Samoa',
'ATA': 'Antarctica',
'ATF': 'French Southern Territories',
'ATG': 'Antigua and Barbuda',
'AUS': 'Australia',
'AUT': 'Austria',
'AZE': 'Azerbaijan',
'BDI': 'Burundi',
'BEL': 'Belgium',
'BEN': 'Benin',
'BES': 'Bonaire, Sint Eustatius and Saba',
'BFA': 'Burkina Faso',
'BGD': 'Bangladesh',
'BGR': 'Bulgaria',
'BHR': 'Bahrain',
'BHS': 'Bahamas (the)',
'BIH': 'Bosnia and Herzegovina',
'BLM': 'Saint Barthelemy',
'BLR': 'Belarus',
'BLZ': 'Belize',
'BMU': 'Bermuda',
'BOL': 'Bolivia (Plurinational State of)',
'BRA': 'Brazil',
'BRB': 'Barbados',
'BRN': 'Brunei',
'BTN': 'Bhutan',
'BVT': 'Bouvet Island',
'BWA': 'Botswana',
'CAF': 'Central African Republic (the)',
'CAN': 'Canada',
'CCK': 'Cocos (Keeling) Islands (the)',
'CHE': 'Switzerland',
'CHL': 'Chile',
'CHN': 'China',
'CIV': 'Cote d\'Ivoire',
'CMR': 'Cameroon',
'COD': 'Congo (the Democratic Republic of the)',
'COG': 'Congo (the)',
'COK': 'Cook Islands (the)',
'COL': 'Colombia',
'COM': 'Comoros (the)',
'CPV': 'Cabo Verde',
'CRI': 'Costa Rica',
'CUB': 'Cuba',
'CUW': 'Curaçao',
'CXR': 'Christmas Island',
'CYM': 'Cayman Islands (the)',
'CYP': 'Cyprus',
'CZE': 'Czechia',
'DEU': 'Germany',
'DJI': 'Djibouti',
'DMA': 'Dominica',
'DNK': 'Denmark',
'DOM': 'Dominican Republic (the)',
'DZA': 'Algeria',
'ECU': 'Ecuador',
'EGY': 'Egypt',
'ERI': 'Eritrea',
'ESH': 'Western Sahara*',
'ESP': 'Spain',
'EST': 'Estonia',
'ETH': 'Ethiopia',
'FIN': 'Finland',
'FJI': 'Fiji',
'FLK': 'Falkland Islands (the) [Malvinas]',
'FRA': 'France',
'FRO': 'Faroe Islands (the)',
'FSM': 'Micronesia (Federated States of)',
'GAB': 'Gabon',
'GBR': 'United Kingdom',
'GEO': 'Georgia',
'GGY': 'Guernsey',
'GHA': 'Ghana',
'GIB': 'Gibraltar',
'GIN': 'Guinea',
'GLP': 'Guadeloupe',
'GMB': 'Gambia (the)',
'GNB': 'Guinea-Bissau',
'GNQ': 'Equatorial Guinea',
'GRC': 'Greece',
'GRD': 'Grenada',
'GRL': 'Greenland',
'GTM': 'Guatemala',
'GUF': 'French Guiana',
'GUM': 'Guam',
'GUY': 'Guyana',
'HKG': 'Hong Kong',
'HMD': 'Heard Island and McDonald Islands',
'HND': 'Honduras',
'HRV': 'Croatia',
'HTI': 'Haiti',
'HUN': 'Hungary',
'IDN': 'Indonesia',
'IMN': 'Isle of Man',
'IND': 'India',
'IOT': 'British Indian Ocean Territory (the)',
'IRL': 'Ireland',
'IRN': 'Iran',
'IRQ': 'Iraq',
'ISL': 'Iceland',
'ISR': 'Israel',
'ITA': 'Italy',
'JAM': 'Jamaica',
'JEY': 'Jersey',
'JOR': 'Jordan',
'JPN': 'Japan',
'KAZ': 'Kazakhstan',
'KEN': 'Kenya',
'KGZ': 'Kyrgyzstan',
'KHM': 'Cambodia',
'KIR': 'Kiribati',
'KNA': 'Saint Kitts and Nevis',
'KOR': 'Korea, South',
'KWT': 'Kuwait',
'LAO': 'Lao People\'s Democratic Republic (the)',
'LBN': 'Lebanon',
'LBR': 'Liberia',
'LBY': 'Libya',
'LCA': 'Saint Lucia',
'LIE': 'Liechtenstein',
'LKA': 'Sri Lanka',
'LSO': 'Lesotho',
'LTU': 'Lithuania',
'LUX': 'Luxembourg',
'LVA': 'Latvia',
'MAC': 'Macau',
'MAF': 'Saint Martin (French part)',
'MAR': 'Morocco',
'MCO': 'Monaco',
'MDA': 'Moldova (the Republic of)',
'MDG': 'Madagascar',
'MDV': 'Maldives',
'MEX': 'Mexico',
'MHL': 'Marshall Islands (the)',
'MKD': 'North Macedonia',
'MLI': 'Mali',
'MLT': 'Malta',
'MMR': 'Myanmar',
'MNE': 'Montenegro',
'MNG': 'Mongolia',
'MNP': 'Northern Mariana Islands (the)',
'MOZ': 'Mozambique',
'MRT': 'Mauritania',
'MSR': 'Montserrat',
'MTQ': 'Martinique',
'MUS': 'Mauritius',
'MWI': 'Malawi',
'MYS': 'Malaysia',
'MYT': 'Mayotte',
'NAM': 'Namibia',
'NCL': 'New Caledonia',
'NER': 'Niger (the)',
'NFK': 'Norfolk Island',
'NGA': 'Nigeria',
'NIC': 'Nicaragua',
'NIU': 'Niue',
'NLD': 'Netherlands (the)',
'NOR': 'Norway',
'NPL': 'Nepal',
'NRU': 'Nauru',
'NZL': 'New Zealand',
'OMN': 'Oman',
'PAK': 'Pakistan',
'PAN': 'Panama',
'PCN': 'Pitcairn',
'PER': 'Peru',
'PHL': 'Philippines (the)',
'PLW': 'Palau',
'PNG': 'Papua New Guinea',
'POL': 'Poland',
'PRI': 'Puerto Rico',
'PRK': 'Korea (the Democratic People\'s Republic of)',
'PRT': 'Portugal',
'PRY': 'Paraguay',
'PSE': 'Palestine, State of',
'PYF': 'French Polynesia',
'QAT': 'Qatar',
'REU': 'Reunion',
'ROU': 'Romania',
'RUS': 'Russian Federation (the)',
'RWA': 'Rwanda',
'SAU': 'Saudi Arabia',
'SDN': 'Sudan (the)',
'SEN': 'Senegal',
'SGP': 'Singapore',
'SGS': 'South Georgia and the South Sandwich Islands',
'SHN': 'Saint Helena, Ascension and Tristan da Cunha',
'SJM': 'Svalbard and Jan Mayen',
'SLB': 'Solomon Islands',
'SLE': 'Sierra Leone',
'SLV': 'El Salvador',
'SMR': 'San Marino',
'SOM': 'Somalia',
'SPM': 'Saint Pierre and Miquelon',
'SRB': 'Serbia',
'SSD': 'South Sudan',
'STP': 'Sao Tome and Principe',
'SUR': 'Suriname',
'SVK': 'Slovakia',
'SVN': 'Slovenia',
'SWE': 'Sweden',
'SWZ': 'Eswatini',
'SXM': 'Sint Maarten (Dutch part)',
'SYC': 'Seychelles',
'SYR': 'Syrian Arab Republic (the)',
'TCA': 'Turks and Caicos Islands (the)',
'TCD': 'Chad',
'TGO': 'Togo',
'THA': 'Thailand',
'TJK': 'Tajikistan',
'TKL': 'Tokelau',
'TKM': 'Turkmenistan',
'TLS': 'Timor-Leste',
'TON': 'Tonga',
'TTO': 'Trinidad and Tobago',
'TUN': 'Tunisia',
'TUR': 'Turkey',
'TUV': 'Tuvalu',
'TWN': 'Taiwan',
'TZA': 'Tanzania, the United Republic of',
'UGA': 'Uganda',
'UKR': 'Ukraine',
'UMI': 'United States Minor Outlying Islands (the)',
'URY': 'Uruguay',
'USA': 'US',
'UZB': 'Uzbekistan',
'VAT': 'Holy See',
'VCT': 'Saint Vincent and the Grenadines',
'VEN': 'Venezuela (Bolivarian Republic of)',
'VGB': 'Virgin Islands (British)',
'VIR': 'Virgin Islands (U.S.)',
'VNM': 'Vietnam',
'VUT': 'Vanuatu',
'WLF': 'Wallis and Futuna',
'WSM': 'Samoa',
'YEM': 'Yemen',
'ZAF': 'South Africa',
'ZMB': 'Zambia',
'ZWE': 'Zimbabwe',
}

#Other names for countries
alt_names = {
        # 'China': 'Mainland China',
        'Czech Republic': 'Czechia',
        'UK': 'United Kingdom',
        'South Korea': 'Korea, South',
        # 'Moldova': 'Republic of Moldova',
        # 'Taiwan': 'Taipei and environs',
        'United States': 'US',
        # 'Macao': 'Macao SAR',
        # 'Vietnam': 'Viet Nam',
        # 'Russian Federation': 'Russia',
        # 'Iran': 'Iran (Islamic Republic of)',
        # 'Saint Barthélemy': 'Saint Barthelemy',
        # 'Saint Martin (French part)': 'Saint Martin',
        # 'Palestine': 'occupied Palestinian territory',
        # 'Holy See (Vatican City State)': 'Holy See',
        # 'Brunei Darussalam': 'Brunei',
        # 'Hong Kong': 'Hong Kong SAR',
}
